blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name='blogs_with_date'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# GenericRelation是逆向操作，关联的表可以找到这个本身表
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from read_statistics.models import ReadNumExpandMethod, ReadDetail

# Create your models here.
class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name

    def blog_count(self):
        return self.blog_set.count()

class Blog(models.Model, ReadNumExpandMethod):
    title = models.CharField(max_length=50)
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE)
    content = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    read_details = GenericRelation(ReadDetail)
    created_time = models.DateTimeField(auto_now_add=True)
    last_updated_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "<Blog:%s>" % self.title

    def get_url(self):
        return reverse('blog:blog_detail', kwargs={'blog_pk': self.pk})

    def get_email(self):
        return self.author.email

    class Meta:
        ordering = ['-created_time']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Blog, BlogType
from django.conf import settings
from read_statistics.utils import read_statistics_once_read
from user.forms import LoginForm

# Create your views here.
#分页函数
def get_blogs_common_data(request, blogs_all_list):
    # 分页器
    page_num = request.GET.get('page', 1)
    paginator = Paginator(blogs_all_list, settings.BLOGS_PER_PAGE)
    page_of_blogs = paginator.get_page(page_num)
    current_page_num = page_of_blogs.number
    page_range = list(range(max(1, current_page_num - 2), min(paginator.num_pages + 1, current_page_num + 3)))
    if page_range[0] != 1:
        page_range.insert(0, 1)
        if page_range[1] - page_range[0] >= 2:
            page_range.insert(1, '...')
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)
        if page_range[-1] - page_range[-2] >= 2:
            page_range.insert(-1, '...')
    # 获取日期归档的博客统计数量
    blog_dates = dict()
    all_dates = Blog.objects.dates('created_time', 'month', order='DESC')
    for blogs_date in all_dates:
        blogs_count = Blog.objects.filter(created_time__year=blogs_date.year,
                                          created_time__month=blogs_date.month).count()
        blog_dates[blogs_date] = blogs_count

    # 获取公共的数据
    context = dict()
    context['blogs'] = page_of_blogs
    context['page_range'] = page_range
        # 运用annotate方法给对象添加注释
    #context['blog_types'] = BlogType.objects.annotate(blog_count=Count('blog'))
    context['blog_types'] = BlogType.objects.all()
    context['blog_dates'] = blog_dates
    return context

def blog_list(request):
    blogs_all_list = Blog.objects.all()
    context = get_blogs_common_data(request, blogs_all_list)
    return render(request, 'blog/blog_list.html', context)

def blogs_with_type(request, blog_type_pk):
    blog_type = get_object_or_404(BlogType, pk=blog_type_pk)
    blogs_all_list = Blog.objects.filter(blog_type=blog_type)
    context = get_blogs_common_data(request, blogs_all_list)
    context['blog_type'] = blog_type
    return render(request, 'blog/blogs_with_type.html', context)

def blogs_with_date(request, year, month):
    blogs_all_list = Blog.objects.filter(created_time__year=year, created_time__month=month)
    context = get_blogs_common_data(request, blogs_all_list)
    context['blogs_with_date'] = '%s年%s' % (year, month)
    return render(request, 'blog/blogs_with_date.html', context)

def blog_detail(request, blog_pk):
    blog = get_object_or_404(Blog, pk=blog_pk)
    read_cookie_key = read_statistics_once_read(request, blog)
    context = dict()
    context['blog'] = blog
    context['blog_author'] = blog.author.get_nickname_or_username()
    context['login_form'] = LoginForm()
    context['pre_blog'] = Blog.objects.filter(created_time__gt=blog.created_time).last()
    context['next_blog'] = Blog.objects.filter(created_time__lt=blog.created_time).first()
    context['blog_dates'] = Blog.objects.dates('created_time', 'month', order='DESC')
    response = render(request, 'blog/blog_detail.html', context)
    response.set_cookie(read_cookie_key, 'true')
    return response

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% load static %}
{% load comment_tags %}
{% load likes_tags %}
{# 页面标题 #}
{% block title %}
    我的网站
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'blog/blog.css' %}">
{% endblock %}

{% block nav_blog_active %}active{% endblock %}

{# 页面内容 #}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% block blog_list_title %}博客列表{% endblock %}
                    </div>
                    <div class="panel-body">
                        {% for blog in blogs %}
                            <div class="blog">
                                <h3><a href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title }}</a></h3>
                                <p class="blog-info">
                                    <span class="glyphicon glyphicon-tag" aria-hidden="true"></span><a href="{% url 'blog:blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type.type_name }}</a>&nbsp;&nbsp;
                                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>{{ blog.created_time|date:"Y-m-d H:n:s" }}&nbsp;&nbsp;
                                    阅读（{{ blog.get_read_num }}）&nbsp;&nbsp;
                                    评论（{% get_comment_count blog %}）&nbsp;&nbsp;
                                    点赞（{% get_like_count blog %}）
                                </p>
                                <p>{{ blog.content|striptags|truncatechars:120 }}</p>
                            </div>
                        {% empty %}
                            <div  class="blog">
                                <h3>--- 暂无博客，尽请期待 ---</h3>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div aria-label="Page navigation" class="paginator">
                    <ul class="pagination">
                        {# 这里判断当前有没有上一页，没有就不让点上一页按钮 #}
                        <li>
                            {% if blogs.has_previous %}
                                <a href="?page={{ blogs.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% else %}
                                <span aria-hidden="true">&laquo;</span>
                            {% endif %}
                        </li>
                        {# 全部页码 #}
                        {% for page_num in page_range %}
                            {% if page_num == blogs.number %}
                                <li class="active"><span>{{ page_num }}</span></li>
                            {% else %}
                                {% if page_num == '...' %}
                                    <li><span>{{ page_num }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {# 这里判断当前有没有下一页，没有就不让点下一页按钮 #}
                        <li>
                            {% if blogs.has_next %}
                                <a href="?page={{ blogs.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            {% else %}
                                <span aria-hidden="true">&raquo;</span>
                            {% endif %}
                        </li>
                    </ul>
                    <p>
                        共有篇{{ blogs.paginator.object_list|length }}博客，
                        当前第{{ blogs.number }}页，共{{ blogs.paginator.num_pages }}页
                    </p>
                </div>
            </div>
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        博客分类
                    </div>
                    <div class="panel-body">
                        <ul class="blog-types">
                            {% for blog_type in blog_types %}
                                <li>
                                    <a href="{% url 'blog:blogs_with_type' blog_type.pk %}">
                                        {{ blog_type.type_name }}({{ blog_type.blog_count }})
                                    </a>
                                </li>
                            {% empty %}
                                <li>暂无分类</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        日期归档
                    </div>
                    <div class="panel-body">
                        <ul class="blog_dates">
                            {% for blog_date, blog_count in blog_dates.items %}
                                <li>
                                    <a href="{% url 'blog:blogs_with_date' blog_date.year blog_date.month %}">
                                        {{ blog_date|date:"Y年m月" }}({{ blog_count }})
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogs_with_date.html
{% extends 'blog/blog_list.html' %}

{# 页面标题 #}
{% block title %}
    {{ blogs_with_date }}
{% endblock %}

{% block blog_list_title %}
    日期归档：{{ blogs_with_date }}（一共有篇{{ blogs.paginator.object_list|length }}博客）
{% endblock %}

blog/templates/blog/blogs_with_type.html
{% extends 'blog/blog_list.html' %}

{# 页面标题 #}
{% block title %}
    {{ blog_type.type_name }}
{% endblock %}

{% block blog_list_title %}
    分类：{{ blog_type.type_name }}（一共有篇{{ blogs.paginator.object_list|length }}博客）
{% endblock %}