blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name='blogs_with_date'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('login_for_modal/', views.login_for_modal, name='login_for_modal'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('user_info/', views.user_info, name='user_info'),
    path('change_nickname/', views.change_nickname, name='change_nickname'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_verfication_code/', views.send_verfication_code, name='send_verfication_code'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('change_password/', views.change_password, name='change_password'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    {% block header_extends %}{% endblock %}
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">个人博客网站</a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="{% block nav_home_active %}{% endblock %}">
                        <a href="{% url 'home' %}">首页</a>
                    </li>
                    <li class="{% block nav_blog_active %}{% endblock %}">
                        <a href="{% url 'blog:blog_list' %}">博客</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                        <li>
                            <a href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a>
                        </li>
                        <li>
                            <a href="{% url 'user:login' %}?from={{ request.get_full_path }}">登录</a>
                        </li>
                    {% else %}
                        <li class="dropdown">
                            <a href="#" id="user_id" class="dropdown-toggle" data-toggle="dropdown" role="button">{{ user.get_nickname_or_username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'user:user_info' %}">个人资料</a></li>
                                {% if user.is_staff or user.is_superuser %}
                                    <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                                {% endif %}
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'user:logout' %}?from={{ request.get_full_path }}">退出</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

    {% block content %}{% endblock %}
    {% block script_extends %}{% endblock %}
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    我的网站 | 错误
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    {{ message }}<a href="{{ redirect_to }}">返回</a>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-5 col-xs-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span id="tip" class="text-danger">{{ form.non_field_errors }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block other_buttons %}{% endblock %}
                            </div>
                            <div class="pull-right">
                                <input type="submit" value="{{ submit_text }}" class="btn btn-primary">
                                <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style type="text/css">
    div.panel-body span li {
        list-style-type: none;
    }
    </style>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    我的网站 | 首页
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="home-container">
        <div class="display-content">
            <div class="home-content">
                <h3 >这是我的记事网站，欢迎亲爱的前来审查！</h3>
            </div>
            <div id="container" style="width: 600px;height:400px;"></div>
        </div>
        <!-- 今天24小时内的热门博客 -->
        <div class="hot-data">
            <h3>今天热门博客</h3>
            <ul>
                {% for hot_data in today_hot_data %}
                    <li><a href="{% url 'blog:blog_detail'  hot_data.object_id %}">{{ hot_data.content_object.title }}</a>（{{ hot_data.read_num }}）</li>
                {% empty %}
                    <li>今天暂无热门博客</li>
                {% endfor %}
            </ul>
            <h3>昨天热门博客</h3>
            <ul>
                {% for hot_data in yesterday_hot_data %}
                    <li><a href="{% url 'blog:blog_detail'  hot_data.object_id %}">{{ hot_data.content_object.title }}</a>（{{ hot_data.read_num }}）</li>
                {% empty %}
                    <li>昨天暂无热门博客</li>
                {% endfor %}
            </ul>
            <h3>近7天热门博客</h3>
            <ul>
                {% for hot_data in week_hot_data %}
                    <li><a href="{% url 'blog:blog_detail'  hot_data.id %}">{{ hot_data.title }}</a>（{{ hot_data.read_num_sum }}）</li>
                {% empty %}
                    <li>近7天暂无热门博客</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <script>
        // 图表配置
        var options = {
            chart: { type: 'line' },
            title: { text: null },
            xAxis: {
                categories: {{ dates|safe }},
                tickmarkPlacement: 'on',
                title: {text: '前一周阅读量变化'}
            },
            yAxis: {
                title: { text: null },
                labels: { enabled: false },
                gridLineDashStyle: 'Dash',
            },
            series: [{
                name: '阅读量',
                data: {{ read_nums }}
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: { enabled: false },
            credits: { enabled: false },
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>
{% endblock %}